version: '3'
services:
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'devops'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'devops'
      MYSQL_ROOT_PASSWORD: 'devops'
    ports:
      - "3308:3306"
    volumes:
      - ./automates.sql:/docker-entrypoint-initdb.d/dump.sql

  unite1: 
    container_name: unite1
    build: ./script/
    environment: 
      - UNITE=1

  unite2: 
    container_name: unite2
    build: ./script/
    environment: 
      - UNITE=2

  unite3: 
    container_name: unite3
    build: ./script/
    environment: 
      - UNITE=3

  unite4: 
    container_name: unite4
    build: ./script/
    environment: 
      - UNITE=4

  unite5: 
    container_name: unite5
    build: ./script/
    environment: 
      - UNITE=5

  unite6: 
    container_name: unite6
    build: ./script/
    environment: 
      - UNITE=6
  
  back:
    container_name: backend
    build: ./back/
    ports:
      - "5000:5000"