FROM node:12.2.0-alpine as build

WORKDIR /website

ENV PATH /website/node_modules/.bin:$PATH

COPY . /website
RUN npm run build

#Server running
FROM nginx:1.16.0-alpine
COPY --from=build /website/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
